config/routes.rb
Rails.application.routes.draw do

  resources :users
  
  resources :minds do
    put :email, on: :member
    resources :neurons
  end

  root 'static_pages#homepage'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/about' => 'static_pages#about'
  get '/zip' => 'neurons#zip'
  get '/minds/:id/completedmind' => 'minds#completedmind', :as => :completedmind
  get '/greatminds' => 'static_pages#greatminds', :as => :greatminds
  get '/openminds' => 'static_pages#openminds', :as => :openminds
  get '/error' => 'static_pages#error', :as => :error


end

app/models/mind.rb
class Mind < ActiveRecord::Base
  
  validates :name, presence: true
  has_one :upvote
  has_many :user_minds
  has_many :users, :through => :user_minds
  has_many :neurons, :through => :user_minds
  attr_reader :user_tokens

  def self.incomplete_minds
    where(:public => true).select {|mind| mind.neurons.length < 4}
  end

  def self.completed_minds
    where(:public => true).select {|mind| mind.neurons.length >= 4}
  end


  def checkmind(mind,current_user)
    !mind.users.include?(current_user)
  end


  def user_tokens=(ids)
    self.user_ids = ids.split(",")

  end
end

app/controllers/minds_controller.rb
class MindsController < ApplicationController

  before_action :require_login, only: [:create, :update, :show]


  def new
    @mind = Mind.new

  end


  def index
    @minds = Mind.all

  end


  def create
    if Mind.all.length == 0
      @user = current_user
    else
      @user = initial_emails
    end
    @mind = Mind.create(mind_params)
    @mind.user_minds.build(:user_id => current_user.id)
    @mind.save
    upvote = Upvote.create(:mind_id => @mind.id)
    upvote.save



    user_params.each do |k,v|

      userid = v.split(",")

      userid.uniq.each {|x| @mind.users << User.find(x) if !@mind.users.include?(User.find(x))}

    end



    respond_to do |format|
      if @mind.save
        # Tell the UserMailer to send a welcome email after save
        # UserMailer.new_mind(@user).deliver
        format.html { redirect_to(user_path(current_user)) }
        format.json { render json: @user, status: :created, location: @user }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def show

    @mind = Mind.find(params[:id])


    if (!@mind.users.include?(current_user) && @mind.public == false)
      redirect_to error_path
    else
      @lastneuron = @mind.neurons.last
      @neurons = @mind.neurons

      if @neurons.size >= 4
        redirect_to completedmind_path
      end

    end

  end


  def completedmind
    @user = neuron_emails
    @mind = Mind.find(params[:id])
    @neurons = @mind.neurons
    @upvote = @mind.upvote
    # if @mind = @mind
    #   UserMailer.mind_completed(@user).deliver
    # end
  end


  def update

    @mind = Mind.find(params[:id])
    @upvotes = @mind.upvote

    if @mind.upvote == nil
      @upvote = Upvote.create(:mind_id => params[:id])
      count =  @upvote.count += 1
      @upvote.update(:count => count)
      @upvote.users << current_user

    elsif (@mind.upvote != nil && !@mind.upvote.users.include?(current_user))
      count = @mind.upvote.count += 1
      @mind.upvote.update(:count => count)
      @mind.upvote.users << current_user

    elsif @mind.upvote.users.include?(current_user)
      count = @mind.upvote.count -= 1
      @mind.upvote.update(:count => count)
      @mind.upvote.users.delete(current_user)
    end

    respond_to do |format|
      format.html
      format.js
    end

  end



  def initial_emails
    @emails = []

    if Mind.all.last.users.exists?
      Mind.all.last.users.each do |user|
        @emails << user.email
      end
    else
      @email << current_user.email
    end
    @emails
  end

  def neuron_emails
    @emails = []
    @user_ids = []
    @mind = Mind.find(params[:id])
    @neurons = @mind.neurons
    @neurons.each do |user|
      @user_ids << UserMind.find(user.user_mind_id).user_id
    end
    @user_ids.each do |id|
      @emails << User.find(id).email
    end
    @emails
  end

  private

  def mind_params
    params.require(:mind).permit(:name,:public)
  end

  def user_params
    params.require(:mind).permit(:user_tokens)
  end

  def upvote_params
    params.require(:mind).permit(:mind_id)
  end

end

app/helpers/minds_helper.rb
module MindsHelper
end

app/views/minds/_form.html.erb
<%= form_for(@mind) do |f| %>
  <% if @mind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mind.errors.count, "error") %> prohibited this mind from being saved:</h2>
      <ul>
      <% @mind.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/minds/completedmind.html.erb
<%= render :partial => 'layouts/navbar' %>
<ul>
  <% index = 1 %>
  <%@neurons.each do |neuron|%>
    <li> 
    <% @user = User.find(neuron.user_mind.user_id) %>
    <a href="#neuron-<%=index%>" class="smoothScroll"><%= neuron.name %></a> made by <%= @user.name %>

    </li>
    <% index += 1 %>
  <%end%>


</ul>


<table>
  <tr>
  <% i = 1 %>
  <%@neurons.each do |neuron|%>
      <td id = "neuron-<%=i%>" >
      <img src = "data:image/png;base64,<%=neuron.image%>"> <br> <br><br><br><br><br>
      <% i += 1 %>
      </td>
  <%end%>
    
  </tr>

</table>  
<%= image_tag "icon_2751.png", id: "upvote-icon" %>



<strong><span id = "upvote-count">Upvotes: <%=@upvote.count%> </span></strong>


<% if @mind.upvote == nil || !@mind.upvote.users.include?(current_user) %>

<% upvote = "Upvote" %>

<% elsif @mind.upvote.users.include?(current_user) %>

  <% upvote = "Upvoted"%>

<% end %>

<br>

<br>
<%= button_to upvote, mind_path,id: "upvote-button-complete", :method => :patch, :remote => true,:class => "btn btn-default btn-submit submit" %>

app/views/minds/create.js.erb
function addMind() { 


  var id = parseInt(<%= j @mind.id.to_s %>)
  var name = "<%= j @mind.name %>";
  var publicmind = "<%= j @mind.public.to_s %>"
  var mindstatus



  if (publicmind === "true"){
    mindstatus = "Open Mind";
  }
  else{
    mindstatus = "Closed Mind"
  }



  var appendItem = '<li><a href = /minds/'+id+'>'+name+'</a>'+' - '+mindstatus+'</li>'

  $('#open-mind-list').append(appendItem);

  $('#mind_name').val('');

 $("li.token-input-token-facebook").remove();

  }


// if($("#mind_name").val() !== null){
  $('#mind-create-button').on('click', addMind());
// }

app/views/minds/edit.html.erb
<h1>Editing mind</h1>

<%= render 'form' %>

<%= link_to 'Show', @mind %> |
<%= link_to 'Back', minds_path %>

app/views/minds/index.html.erb
<h1>Listing minds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @minds.each do |mind| %>
      <tr>
        <td><%= mind.name %></td>
        <td><%= link_to 'Show', mind %></td>
        <td><%= link_to 'Edit', edit_mind_path(mind) %></td>
        <td><%= link_to 'Destroy', mind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mind', new_mind_path %>

app/views/minds/new.html.erb
<h1>New mind</h1>

<%= render 'form' %>



<%= link_to 'Back', minds_path %>

app/views/minds/show.html.erb
<%= render :partial => 'layouts/navbar' %>

  <h1 style = "text-align:center;"> <strong><%= @mind.name%></strong> <br> has
    <% if  4 - @neurons.size > 1 %>
      <strong><%= 4 - @neurons.size %></strong> neurons left </h1> <br>
    <% elsif 4 - @neurons.size == 1 %>
      <strong><%= 4 - @neurons.size %></strong> neuron left </h1> <br>
    <% end %>

  <table align = "center" >
    <tr>
      <td id = "td-partial-neuron">
        <div id = "partial-neuron" >
        <img id = "neurons" src="data:image/png;base64, <% if @neurons.size == 0 %> <%else%> <%= @lastneuron.image %> <% end %>" >
        </div>
      </td>
      <td>
        <canvas id ="processing-canvas"> </canvas>
      </td>
    </tr>

</table>
<br>


<div id = "canvas-options">

    <div id = "color-options">
   <strong>Colors:</strong>
    <div id="red"></div>
    <div id="orange"></div>
    <div id="yellow"></div>
    <div id="green"></div>
    <div id="blue"></div>
    <div id="purple"></div>
    <div id="black"></div>
    <div id="white"></div>
</div>
<div id = "eraser-options" >
    <strong>Eraser:</strong>
    <img id="eraser" src="/assets/icon_3715.png">
</div>

<div id = "draw-opacity" >   
 <strong>Opacity:</strong>
    <div id="opacity-small" title='Light Opacity'></div>
    <div id="opacity-medium" title='Medium Opacity'></div>
    <div id="opacity-large" title='Dark Opacity'></div>
  </div>


  <div id = "draw-options" > 
   <strong>Width:</strong>
    <img id="stroke-small" title='Small Stroke' src="/assets/icon_7675.png">
    <img id="stroke-medium" title='Medium Stroke' src="/assets/icon_1170.png">
    <img id="stroke-large" title='Large Stroke' src="/assets/icon_12936.png">
  </div>
  
</div>
<br>

<form id = "neuron-form" align = "center">

<input type = "text" id = "neuron-name" placeholder = "Neuron Name" > <br><br>
<button type = "button" class = "btn black-btn" id="save_button" onclick="saveDrawing()">Submit My Neuron</button>

</form>

 <div class="modal fade" id="neuronModal" tabindex="-1" role="dialog" aria-labelledby="neuronModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h2 class="modal-title" id="modalLabel">ModernMind</h2>
            </div>
            <div id="modal-body">
              
              <br>
                <%= image_tag "icon_14291.png",id: "share-mind"%><br>
                <div id ="modal-body-p"> <p>
                Your neuron has been saved, thank you for contributing! You will recieve an email once the mind has been completed. You can continue drawing or copy and send the link below to a friend to draw together.</p>
                Mind link: 
                  </div>
            </div>

            <div class="modal-footer">
                <button type="button" class='btn black-btn' id="modal-close">Close</button>
        </div>
    </div>
  </div>
</div>

app/views/minds/update.js.erb
function changeUpvote() { 
  

  $('#upvote-count').html("Upvotes: "+'<%= j @upvotes.count.to_s %>')

  $('#upvote-button-complete').val() == "Upvote" ? upvote_Start() : upvoted();


  }

function upvote_Start() {
    $('#upvote-button-complete').val("Upvoted");


  }
  
function upvoted() {
    $('#upvote-button-complete').val("Upvote");

  }


$('#upvote-button').on('click', changeUpvote());