config/routes.rb
Rails.application.routes.draw do

  resources :users
  
  resources :minds do
    put :email, on: :member
    resources :neurons
  end

  root 'static_pages#homepage'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/about' => 'static_pages#about'
  get '/zip' => 'neurons#zip'
  get '/minds/:id/completedmind' => 'minds#completedmind', :as => :completedmind
  get '/greatminds' => 'static_pages#greatminds', :as => :greatminds
  get '/openminds' => 'static_pages#openminds', :as => :openminds
  get '/error' => 'static_pages#error', :as => :error


end

app/models/neuron.rb
class Neuron < ActiveRecord::Base
  # belongs_to :mind
  # belongs_to :contributor, :class_name => "User"
  # belongs_to :user
  belongs_to :user_mind

end

app/controllers/neurons_controller.rb
class NeuronsController < ApplicationController

  before_action :require_login, only: [:index, :create]
  # before_action :require_login, except: :create

  def index
    @neurons = Neuron.all
  end

  def create

    @neuron = Neuron.new(neuron_params)
    # @neuron.user_mind = current_user.id
    @user_mind = UserMind.find_by_user_id_and_mind_id(current_user.id, user_mind_params[:mind_id]) || UserMind.create(:user_id => current_user.id, :mind_id => user_mind_params[:mind_id])
    # @user_mind.user_id = current_user.id
    @neuron.user_mind_id = @user_mind.id


    respond_to do |format|
      if @neuron.save
        format.json { render json: @neuron}
      else
        format.json { render json: "Error", status: :unprocessable_entity }
      end
    end



  end

  private

  def neuron_params

    params.require(:neuron).permit(:name, :image)

  end

  def user_mind_params

    params.require(:user_mind).permit(:mind_id)
  end

end

app/helpers/neurons_helper.rb
module NeuronsHelper
end

app/views/neurons/_form.html.erb
<%= form_for(@neuron) do |f| %>
  <% if @neuron.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@neuron.errors.count, "error") %> prohibited this neuron from being saved:</h2>

      <ul>
      <% @neuron.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/neurons/index.html.erb
<h1>Listing neurons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @neurons.each do |neuron| %>
      <tr>
        <td><%= neuron.name %></td>
        <td><%= link_to 'Show', neuron %></td>
        <td><%= link_to 'Edit', edit_neuron_path(neuron) %></td>
        <td><%= link_to 'Destroy', neuron, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Neuron', new_neuron_path %>