config/routes.rb
Rails.application.routes.draw do

  resources :users
  
  resources :minds do
    put :email, on: :member
    resources :neurons
  end

  root 'static_pages#homepage'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/about' => 'static_pages#about'
  get '/zip' => 'neurons#zip'
  get '/minds/:id/completedmind' => 'minds#completedmind', :as => :completedmind
  get '/greatminds' => 'static_pages#greatminds', :as => :greatminds
  get '/openminds' => 'static_pages#openminds', :as => :openminds
  get '/error' => 'static_pages#error', :as => :error


end

app/views/layouts/_caro.html.erb
<canvas id="caro" data-pause="false"></canvas>

<script>

window.requestAnimationFrame = function() {
	return window.requestAnimationFrame ||
		window.webkitRequestAnimationFrame ||
		window.mozRequestAnimationFrame ||
		window.msRequestAnimationFrame ||
		window.oRequestAnimationFrame ||
		function(f) {
			window.setTimeout(f,1e3/60);
		}
}();

var canvas = document.querySelector('#caro');
var ctx = canvas.getContext('2d');

var W = canvas.width;
var H = canvas.height;

// We want to move/slide/scroll the background
// as the player moves or the game progresses

// Velocity X
var vx = 0;

var img = new Image();
img.src = 'http://www.stephenwiltshire.co.uk/images/Madrid_Panorama_by_Stephen_Wiltshire.jpg';
// img.height = 250px;

(function renderGame() {
	window.requestAnimationFrame(renderGame);
	
	ctx.clearRect(0, 0, W, H);
	
	// ctx.fillStyle = '#333';
	ctx.fillRect(0, 0, W, H);
	
	ctx.drawImage(img, vx, 50);
	ctx.drawImage(img, img.width-Math.abs(vx), 50);


	
	if (Math.abs(vx) > img.width) {
		vx = 0;
	}
	
	vx -= 2;
}());

</script>

app/views/layouts/_navbar.html.erb
        <!-- Header (navigation menu, and logo) -->
        <nav class="navbar navbar-default header-navbar" role="navigation">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="/" >
                                <!-- Logo Image -->
                                <%= image_tag "png.png", id:"navbar-logo"%>   
                            </a>
                        </div>
                    </div>

                    <div class="col-md-8">
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">                        
                                <!-- <li class="active"><a href="index.html">ModernMind</a></li> -->
                                 <li><a href="/greatminds.html">Great Minds</a></li>
                                <li><a href="/openminds.html">Open Minds</a></li>



                                
                   
                                <!-- login info -->     
                                <% if logged_in? %>
                                  <li><%= link_to current_user.name, user_path(current_user) %></li>
                                  <!-- <li><img src = <%= current_user.image%>></li> -->
                                  <li><%= link_to "Log Out", signout_path %></li>
                                <% else %>
                                <!-- <ul class="nav navbar-nav navbar-right"> -->
                                <li><%= link_to "Log in with Facebook", "/auth/facebook" %></li>
                                <% end %>
                                <!-- <li><a href="contact.html">Luke Demarest</a></li> -->
                            </ul>
                        </div>
                    </div>
                </div><!-- /row -->
            </div><!-- /container -->
        </nav>
        <!-- End Header -->

       

app/views/layouts/_slider.html.erb
        <div id="header-carousel" data-pause="false" class="carousel slide carousel-scroll header-carousel" data-ride="carousel"> 
            <!-- Slider Indicators -->

            <script type="text/javascript">
            $('#header-carousel').carousel({
            interval: .1,
            
        })

            </script>

            <div class="carousel-inner"> 

                <!-- slider text -->
                <div class="carousel-caption header-carousel-caption">
                    <!-- <h1>Modern Mind</h1> -->
                    <!-- <img src="assets/img/icon_11105.png" height="100"><br> -->
                     
                    <!-- Project Link -->
                    <!-- <a href="project-inner.html" class="btn white-btn">Sign In</a> -->
                <canvas id="mind-logo" > </canvas>
                    <!-- <%= link_to "Sign In", "auth/facebook", class:"btn white-btn" %> -->
                </div>   

                <!-- Slider Item (image, link and description for your project in slider) -->        
                <div class="item active"> 
                    <!-- Image -->           
                    <%= image_tag "png-5.png", id:"slider-image-1"%>        
                </div>
                
                <!-- Slider Item (image, link and description for your project in slider) -->
                <div class="item">    
                    <!-- Image -->        
                    <%= image_tag "png-6.png", id:"slider-image-1"%>
                </div>   

                <!-- Slider Item (image, link and description for your project in slider) -->
                <div class="item">    
                    <!-- Image -->        
                    <%= image_tag "png-7.png", id:"slider-image-1"%>
                </div> 

                <!-- Slider Item (image, link and description for your project in slider) -->
                <div class="item">    
                    <!-- Image -->        
                    <%= image_tag "png-8.png", id:"slider-image-1"%>
                </div> 
                       
            </div>   
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js"> <!--<![endif]-->
    <head>
        <title>ModernMind</title>
          <%= csrf_meta_tags %>

          <%= stylesheet_link_tag    'application', media: 'all' %>
          <%= javascript_include_tag 'application' %>

         <script src="/drawingcanvas.js" type="text/processing" data-processing-target="processing-canvas"></script>
          <script src="/mindlogo.js" type="text/processing" data-processing-target="mind-logo"></script>
          
          <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
          <%= analytics_init if Rails.env.production? %>

        <!-- Meta Tags -->
        <meta charset="utf-8">
        <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Favicon-->
        <link rel="icon" type="image/png" href="assets/img/favicon.ico">

        
    </head>
    <body>

    <%= yield %>



                    <div>
                      <br><br><br><br><br><br>
                    </div>
            <!-- Footer -->
    <!--     <div id="footer" class="clearfix" style=" padding: 2px 10px 40px;" >
            <div class="container">   
                <div class="row">  -->
                    <!-- Copyright -->                                    
                <!--     <div class="col-md-4 text-center">
                        <p></p>
                    </div> -->


                    
                    <!-- Up Button -->

                    <!-- <div class="col-md-4 back-to-top"> -->
                        <a href="#">
                            <i class="fa fa-angle-up fa-2x pull-right"></i>
                        </a>
                   <!--  </div>   -->                                                                                                                                               
                <!-- </div> --><!-- /row -->
            <!-- </div> --><!-- /container -->
        <!-- </div> -->
        <!-- End Footer -->
</body>
</html>